"""BIST sembol listesi, dogrulama ve Yahoo Finance sembol donusumu.

Yahoo Finance'te BIST hisseleri `<SEMBOL>.IS` bicimindedir (orn. THYAO.IS).

Asagidaki liste genis bir statik kapsam sunar. Liste eksik olsa bile API
katmani, gecerli bicimde olan herhangi bir sembolu anlik (on-demand) olarak
Yahoo'dan sorgulayabilir; yani buradaki liste yalnizca arka planda periyodik
guncellenen "takip listesi"dir, bir kisit degildir.
"""

from __future__ import annotations

import logging
import re

import httpx

logger = logging.getLogger(__name__)

# Gecerli BIST sembol bicimi: 2-6 buyuk harf/rakam.
_SYMBOL_RE = re.compile(r"^[A-Z0-9]{2,6}$")

YAHOO_SUFFIX = ".IS"

# Genis statik BIST takip listesi (BIST 100 + cok sayida likit hisse).
# Guncel tutmak icin bu kumeyi genisletebilir/duzenleyebilirsiniz.
BIST_SYMBOLS: list[str] = sorted(
    {
        "ACSEL",
        "ADEL",
        "ADESE",
        "AEFES",
        "AFYON",
        "AGHOL",
        "AGROT",
        "AHGAZ",
        "AKBNK",
        "AKCNS",
        "AKENR",
        "AKFGY",
        "AKFYE",
        "AKGRT",
        "AKMGY",
        "AKSA",
        "AKSEN",
        "AKSGY",
        "AKSUE",
        "ALARK",
        "ALBRK",
        "ALCAR",
        "ALCTL",
        "ALFAS",
        "ALGYO",
        "ALKA",
        "ALKIM",
        "ALMAD",
        "ANELE",
        "ANGEN",
        "ANHYT",
        "ANSGR",
        "ARASE",
        "ARCLK",
        "ARDYZ",
        "ARENA",
        "ARSAN",
        "ARZUM",
        "ASELS",
        "ASGYO",
        "ASTOR",
        "ASUZU",
        "ATAGY",
        "ATAKP",
        "ATATP",
        "ATEKS",
        "ATLAS",
        "AVGYO",
        "AVHOL",
        "AVOD",
        "AVPGY",
        "AVTUR",
        "AYCES",
        "AYDEM",
        "AYEN",
        "AYGAZ",
        "AZTEK",
        "BAGFS",
        "BAKAB",
        "BALAT",
        "BANVT",
        "BARMA",
        "BASGZ",
        "BAYRK",
        "BERA",
        "BEYAZ",
        "BFREN",
        "BIENY",
        "BIGCH",
        "BIMAS",
        "BINHO",
        "BIOEN",
        "BIZIM",
        "BJKAS",
        "BLCYT",
        "BMSCH",
        "BMSTL",
        "BNTAS",
        "BOBET",
        "BORLS",
        "BOSSA",
        "BRISA",
        "BRKSN",
        "BRKVY",
        "BRLSM",
        "BRMEN",
        "BRSAN",
        "BRYAT",
        "BSOKE",
        "BTCIM",
        "BUCIM",
        "BURCE",
        "BURVA",
        "BVSAN",
        "CANTE",
        "CASA",
        "CATES",
        "CCOLA",
        "CELHA",
        "CEMAS",
        "CEMTS",
        "CEOEM",
        "CIMSA",
        "CLEBI",
        "CMBTN",
        "CMENT",
        "CONSE",
        "COSMO",
        "CRDFA",
        "CRFSA",
        "CUSAN",
        "CWENE",
        "DAGHL",
        "DAGI",
        "DAPGM",
        "DARDL",
        "DENGE",
        "DERHL",
        "DERIM",
        "DESA",
        "DESPC",
        "DEVA",
        "DGATE",
        "DGGYO",
        "DGNMO",
        "DIRIT",
        "DITAS",
        "DMSAS",
        "DNISI",
        "DOAS",
        "DOBUR",
        "DOCO",
        "DOFER",
        "DOGUB",
        "DOHOL",
        "DOKTA",
        "DURDO",
        "DYOBY",
        "DZGYO",
        "ECILC",
        "ECZYT",
        "EDATA",
        "EDIP",
        "EGEEN",
        "EGEPO",
        "EGGUB",
        "EGPRO",
        "EGSER",
        "EKGYO",
        "EKIZ",
        "EKOS",
        "EKSUN",
        "ELITE",
        "EMKEL",
        "EMNIS",
        "ENERY",
        "ENJSA",
        "ENKAI",
        "ENSRI",
        "EPLAS",
        "ERBOS",
        "ERCB",
        "EREGL",
        "ERSU",
        "ESCAR",
        "ESCOM",
        "ESEN",
        "ETILR",
        "ETYAT",
        "EUHOL",
        "EUKYO",
        "EUPWR",
        "EUREN",
        "EYGYO",
        "FADE",
        "FENER",
        "FLAP",
        "FMIZP",
        "FONET",
        "FORMT",
        "FORTE",
        "FRIGO",
        "FROTO",
        "FZLGY",
        "GARAN",
        "GARFA",
        "GEDIK",
        "GEDZA",
        "GENIL",
        "GENTS",
        "GEREL",
        "GESAN",
        "GLBMD",
        "GLCVY",
        "GLRYH",
        "GLYHO",
        "GMTAS",
        "GOKNR",
        "GOLTS",
        "GOODY",
        "GOZDE",
        "GRNYO",
        "GRSEL",
        "GRTRK",
        "GSDDE",
        "GSDHO",
        "GSRAY",
        "GUBRF",
        "GUNDG",
        "GWIND",
        "GZNMI",
        "HALKB",
        "HATEK",
        "HATSN",
        "HDFGS",
        "HEDEF",
        "HEKTS",
        "HKTM",
        "HLGYO",
        "HRKET",
        "HTTBT",
        "HUBVC",
        "HUNER",
        "HURGZ",
        "ICBCT",
        "ICUGS",
        "IDGYO",
        "IEYHO",
        "IHAAS",
        "IHEVA",
        "IHGZT",
        "IHLAS",
        "IHLGM",
        "IHYAY",
        "IMASM",
        "INDES",
        "INFO",
        "INGRM",
        "INTEM",
        "INVEO",
        "INVES",
        "IPEKE",
        "ISATR",
        "ISBIR",
        "ISBTR",
        "ISCTR",
        "ISDMR",
        "ISFIN",
        "ISGSY",
        "ISGYO",
        "ISKPL",
        "ISMEN",
        "ISSEN",
        "ISYAT",
        "IZENR",
        "IZFAS",
        "IZINV",
        "IZMDC",
        "JANTS",
        "KAPLM",
        "KAREL",
        "KARSN",
        "KARTN",
        "KARYE",
        "KATMR",
        "KAYSE",
        "KBORU",
        "KCAER",
        "KCHOL",
        "KENT",
        "KERVN",
        "KERVT",
        "KFEIN",
        "KGYO",
        "KIMMR",
        "KLGYO",
        "KLKIM",
        "KLMSN",
        "KLNMA",
        "KLRHO",
        "KLSER",
        "KLSYN",
        "KMPUR",
        "KNFRT",
        "KOCMT",
        "KONKA",
        "KONTR",
        "KONYA",
        "KOPOL",
        "KORDS",
        "KOZAA",
        "KOZAL",
        "KRDMA",
        "KRDMB",
        "KRDMD",
        "KRGYO",
        "KRONT",
        "KRPLS",
        "KRSTL",
        "KRTEK",
        "KRVGD",
        "KSTUR",
        "KTLEV",
        "KTSKR",
        "KUTPO",
        "KUYAS",
        "KZBGY",
        "KZGYO",
        "LIDER",
        "LIDFA",
        "LILAK",
        "LINK",
        "LKMNH",
        "LMKDC",
        "LOGO",
        "LRSHO",
        "LUKSK",
        "MAALT",
        "MACKO",
        "MAGEN",
        "MAKIM",
        "MAKTK",
        "MANAS",
        "MARBL",
        "MARKA",
        "MARTI",
        "MAVI",
        "MEDTR",
        "MEGAP",
        "MEGMT",
        "MEKAG",
        "MEPET",
        "MERCN",
        "MERIT",
        "MERKO",
        "METRO",
        "METUR",
        "MGROS",
        "MHRGY",
        "MIATK",
        "MIPAZ",
        "MMCAS",
        "MNDRS",
        "MNDTR",
        "MOBTL",
        "MOGAN",
        "MPARK",
        "MRGYO",
        "MRSHL",
        "MSGYO",
        "MTRKS",
        "MTRYO",
        "MZHLD",
        "NATEN",
        "NETAS",
        "NIBAS",
        "NTGAZ",
        "NTHOL",
        "NUGYO",
        "NUHCM",
        "OBAMS",
        "ODAS",
        "OFSYM",
        "ONCSM",
        "ORCAY",
        "ORGE",
        "ORMA",
        "OSMEN",
        "OSTIM",
        "OTKAR",
        "OTTO",
        "OYAKC",
        "OYAYO",
        "OYLUM",
        "OZGYO",
        "OZKGY",
        "OZRDN",
        "OZSUB",
        "PAGYO",
        "PAMEL",
        "PAPIL",
        "PARSN",
        "PASEU",
        "PATEK",
        "PCILT",
        "PEGYO",
        "PEKGY",
        "PENGD",
        "PENTA",
        "PETKM",
        "PETUN",
        "PGSUS",
        "PINSU",
        "PKART",
        "PKENT",
        "PLTUR",
        "PNLSN",
        "PNSUT",
        "POLHO",
        "POLTK",
        "PRDGS",
        "PRKAB",
        "PRKME",
        "PRZMA",
        "PSDTC",
        "PSGYO",
        "QUAGR",
        "RALYH",
        "RAYSG",
        "REEDR",
        "RGYAS",
        "RODRG",
        "ROYAL",
        "RTALB",
        "RUBNS",
        "RYGYO",
        "RYSAS",
        "SAFKR",
        "SAHOL",
        "SANEL",
        "SANFM",
        "SANKO",
        "SARKY",
        "SASA",
        "SAYAS",
        "SDTTR",
        "SEGYO",
        "SEKFK",
        "SEKUR",
        "SELEC",
        "SELGD",
        "SELVA",
        "SEYKM",
        "SILVR",
        "SISE",
        "SKBNK",
        "SKTAS",
        "SKYLP",
        "SKYMD",
        "SMART",
        "SMRTG",
        "SNGYO",
        "SNICA",
        "SNKRN",
        "SODSN",
        "SOKE",
        "SOKM",
        "SONME",
        "SRVGY",
        "SUMAS",
        "SUNTK",
        "SURGY",
        "SUWEN",
        "TABGD",
        "TARKM",
        "TATEN",
        "TATGD",
        "TAVHL",
        "TBORG",
        "TCELL",
        "TDGYO",
        "TEKTU",
        "TERA",
        "TETMT",
        "TEZOL",
        "TGSAS",
        "THYAO",
        "TKFEN",
        "TKNSA",
        "TLMAN",
        "TMPOL",
        "TMSN",
        "TNZTP",
        "TOASO",
        "TRCAS",
        "TRGYO",
        "TRILC",
        "TSGYO",
        "TSKB",
        "TSPOR",
        "TTKOM",
        "TTRAK",
        "TUCLK",
        "TUKAS",
        "TUPRS",
        "TUREX",
        "TURGG",
        "TURSG",
        "ULAS",
        "ULKER",
        "ULUFA",
        "ULUSE",
        "ULUUN",
        "UMPAS",
        "UNLU",
        "USAK",
        "UZERB",
        "VAKBN",
        "VAKFN",
        "VAKKO",
        "VANGD",
        "VBTYZ",
        "VERTU",
        "VERUS",
        "VESBE",
        "VESTL",
        "VKGYO",
        "VKING",
        "YAPRK",
        "YATAS",
        "YAYLA",
        "YBTAS",
        "YEOTK",
        "YESIL",
        "YGGYO",
        "YGYO",
        "YKBNK",
        "YKSLN",
        "YONGA",
        "YUNSA",
        "YYAPI",
        "YYLGD",
        "ZEDUR",
        "ZOREN",
        "ZRGYO",
    }
)


def normalize(symbol: str) -> str:
    """Sembolu buyuk harfe cevirir, bosluk ve olasi `.IS` ekini temizler."""
    if symbol is None:
        return ""
    s = symbol.strip().upper()
    if s.endswith(YAHOO_SUFFIX):
        s = s[: -len(YAHOO_SUFFIX)]
    return s


def is_valid_symbol(symbol: str) -> bool:
    """Sembol gecerli BIST bicminde mi? (Injection/kotu girdiye karsi kalkan.)"""
    return bool(_SYMBOL_RE.match(normalize(symbol)))


def to_yahoo(symbol: str) -> str:
    """BIST sembolunu Yahoo Finance bicimine cevirir: THYAO -> THYAO.IS"""
    return f"{normalize(symbol)}{YAHOO_SUFFIX}"


def from_yahoo(yahoo_symbol: str) -> str:
    """Yahoo sembolunden BIST sembolune: THYAO.IS -> THYAO"""
    return normalize(yahoo_symbol)


def default_watchlist() -> list[str]:
    """Statik BIST_SYMBOLS + EXTRA_SYMBOLS birlesimi (sirali).

    Statik liste HER ZAMAN taban kalir (kayipsizlik); EXTRA_SYMBOLS yalnizca ekler.
    """
    from .config import settings

    extra = {normalize(s) for s in settings.extra_symbols if is_valid_symbol(s)}
    return sorted(set(BIST_SYMBOLS) | extra)


async def fetch_universe() -> list[str]:
    """TradingView scanner'dan TUM BIST hisse sembollerini enumerate eder.

    Govde `type=stock` filtreler; yanit satirlari s="BIST:XXX" bicimindedir.
    XXX cikarilip is_valid_symbol'den gecirilir. Enumerate GUVENILMEZSE (ag/JSON
    hatasi) veya sonuc symbol_universe_min_count altinda ise BOS liste doner (guard):
    boylece bozuk/kismi bir evren, cagiran tarafta mevcut listeyi daraltamaz.
    """
    from .config import settings
    from .providers.tradingview import _HEADERS, _SCANNER_URL

    body = {
        "filter": [{"left": "type", "operation": "equal", "right": "stock"}],
        "symbols": {"query": {"types": []}},
        "columns": ["name"],
        "range": [0, 2000],
    }
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            resp = await client.post(_SCANNER_URL, json=body, headers=_HEADERS)
        resp.raise_for_status()
        rows = resp.json().get("data") or []
    except Exception as exc:
        logger.warning("TradingView evren cekimi hatasi: %s", exc)
        return []

    out: set[str] = set()
    for row in rows:
        ticker = row.get("s") if isinstance(row, dict) else None
        # Yalnizca BIST borsasi: yanit karisirsa (NASDAQ:AAPL vb.) yabanci
        # semboller takip listesine sizmasin.
        if not isinstance(ticker, str) or not ticker.startswith("BIST:"):
            continue
        bist = normalize(ticker.split(":", 1)[1])
        if is_valid_symbol(bist):
            out.add(bist)

    result = sorted(out)
    if len(result) < settings.symbol_universe_min_count:
        logger.warning(
            "TradingView evreni yetersiz: %d < %d, guard reddetti",
            len(result),
            settings.symbol_universe_min_count,
        )
        return []
    return result
